services:
  library_db:
    image: postgres
    container_name: library_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dockerdb_library
      - POSTGRES_PASSWORD=dockerdb_library
      - POSTGRES_DB=library
    volumes:
      - pgdata:/data/postgres
  app:
    container_name: library_api
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/app
    env_file:
      - .env
    command: npm run dev
    ports:
      - 3000:3000
    links:
      - library_db
    depends_on:
      - library_db
volumes:
  pgdata:
    driver: local
